dist: bionic
language: minimal

install:
    - sudo apt-get update
    - sudo apt-get install python3 python3-pip python3-venv -y
    - python3 -V

script:
    - chmod +x script/*.sh
    - script/venv.sh
    - script/gitignore.sh
    - script/surge-ad.sh
    - script/surge-gfwlist.sh
    - script/dnscrypt-proxy-forwarding.sh
    - script/privoxy-gfwlist.sh
    - script/chinadns-chnroute.sh
    - script/dnsmasq-china-domains.sh

deploy:
    provider: pages
    skip-cleanup: true
    target-branch: gh-pages
    github-token: $GITHUB_TOKEN
    keep-history: true
    verbose: true
    on:
        branch: master
