language: minimal

install:
    - sudo apt-get update
    - sudo apt-get install python python-pip python3-venv -y
    - sudo pip install gfwlist2privoxy

script:
    - chmod +x script/*.sh
    - script/gitignore.sh
    - script/surge-ad.sh
    - script/dnscrypt-proxy-forwarding.sh
    - script/privoxy-gfwlist.sh
    - script/chinadns-chnroute.sh

deploy:
    provider: pages
    skip-cleanup: true
    target-branch: gh-pages
    github-token: $GITHUB_TOKEN
    keep-history: true
    verbose: true
    on:
        branch: master
